### ISSUE TITLE
Today widget take a long time to update data

### ISSUE THREAD

**Issue by duyquang91** [eldoogy/PowerData#1]
I have tested on today widget and it take a long time to update data, on main App working perfect

**Comment by eldade** [comment]
How are you using it from the widget? Can you post a sample? 

Also, is it taking a long time every time you launch the widget, or only after you dismiss the notification center and then come back later?

**Comment by duyquang91** [comment]
#import "TodayViewController.h"
#import <NotificationCenter/NotificationCenter.h>

@interface TodayViewController () <NCWidgetProviding>
@end
@implementation TodayViewController
- (void)viewDidLoad {
  [super viewDidLoad];
  }

-(void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];

```
UIDeviceListener *listener = [UIDeviceListener sharedUIDeviceListener];
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(listenerDataUpdated:) name: kUIDeviceListenerNewDataNotification object:nil];
[listener startListener];
```

}
- (void)listenerDataUpdated: (NSNotification *) notification
  {
  NSDictionary *data = notification.userInfo;
  //My code here to update data
  }
- (void)didReceiveMemoryWarning {
  [super didReceiveMemoryWarning];
  // Dispose of any resources that can be recreated.
  }
- (void)widgetPerformUpdateWithCompletionHandler:(void (^)(NCUpdateResult))completionHandler {
  
  completionHandler(NCUpdateResultNewData);
  }

@end

**Comment by duyquang91** [comment]
first launch is working perfect, then I dissmiss and show the widget again, it take long time for "(void)listenerDataUpdated: (NSNotification *) notification" response

**Comment by eldade** [comment]
Well, the data is only updated every 20 seconds or so. There probably just isn't any new data to present. One thing you could do is call stopListener whenever they exit the Notification Center, then call startListener again whenever they reopen it. That way you'd always get the latest available data as soon as they come back.

**Comment by duyquang91** [comment]
thanks, I set stopListener when viewWillDisappear and it working perfect
